# Generated by Django 3.1 on 2021-10-10 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20211010_0317'),
        ('üçkodu', '0003_auto_20211010_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ückodu',
            name='dahil_olmuşdur',
            field=models.DateField(blank=True, null=True, verbose_name='Daxil olma tarixi'),
        ),
        migrations.AlterField(
            model_name='ückodu',
            name='instansiya_mahkemesi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ückodumahkeme', to='apps.i̇nstansiyamahkemesimodel', verbose_name='1-ci instansiya məhkəməsi'),
        ),
        migrations.AlterField(
            model_name='ückodu',
            name='instansiya_mahkemesi_hakimi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ückodumahkemehakimi', to='apps.instansiyamahkemesihakimimodel', verbose_name='1-ci instansiya məhkəməsi hakimi'),
        ),
        migrations.AlterField(
            model_name='ückodu',
            name='növ',
            field=models.CharField(choices=[('_____', '______'), ('3 ', '3'), ('3-1', '3-1')], default='______', max_length=5000),
        ),
        migrations.AlterField(
            model_name='ückodu',
            name='qərarın_baxılma_nəticəsi',
            field=models.CharField(choices=[('_____', '______'), ('3 ', '3'), ('3-1', '3-1')], default='______', max_length=50000),
        ),
    ]
