# Generated by Django 3.1 on 2021-10-10 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20211010_0317'),
        ('üçkodu', '0004_auto_20211010_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ückodu',
            name='iki_instansiya_mahkemesi_hakimi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ückodumahkemehakimiiki', to='apps.ikinciinstansiyamahkemesihakimimodel', verbose_name='Apellyasiya məhkəməsinin hakimi'),
        ),
        migrations.AlterField(
            model_name='ückodu',
            name='qərarın_baxılma_nəticəsi',
            field=models.CharField(choices=[('_____', '______'), ('inzibati cərimə;', 'inzibati cərimə;'), ('ix-nın törədilməsində alət və ya ix-nın bilavasitə obyekti olmuş predmetin ödənişlə alınması;', 'ix-nın törədilməsində alət və ya ix-nın bilavasitə obyekti olmuş predmetin ödənişlə alınması;'), ('xüsusi hüququnun məhdudlaşdırılması;', 'xüsusi hüququnun məhdudlaşdırılması;'), ('AR-nın hüdudlarından kənara inzibati qaydada çıxartma;', 'AR-nın hüdudlarından kənara inzibati qaydada çıxartma;'), ('inzibati həbs.', 'inzibati həbs.'), ('İşin icraatına xitam verildi', 'İşin icraatına xitam verildi'), ('ix-nın törədilməsində alət və ya ix-nın bilavasitə obyekti olmuş predmetin müsadirəsi', 'ix-nın törədilməsində alət və ya ix-nın bilavasitə obyekti olmuş predmetin müsadirəsi')], default='______', max_length=50000),
        ),
    ]
