# Generated by Django 3.1 on 2021-10-01 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0002_auto_20210925_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='altıkodu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('işin_nömrəsi', models.CharField(blank=True, max_length=50000, null=True)),
                ('növ', models.CharField(choices=[('_____', '______'), ('6', '6'), ('6-1', '6-1')], default='______', max_length=50000)),
                ('daxil_olduğu_tarix', models.DateField(blank=True, null=True)),
                ('şikayətlə_müraciət_edən_şəxs', models.CharField(blank=True, max_length=50000, null=True)),
                ('şikayət_verilmişdir', models.CharField(choices=[('_____', '______'), ('01 - təhqiqatçının (onun səlahiyyətlərini həyata keçirən şəxsin)', '01 - təhqiqatçının (onun səlahiyyətlərini həyata keçirən şəxsin)'), ('02 - tutulmanı və ya tutulan şəxsin həbsdə saxlanılma yerlərində saxlanılmasını həyata keçirən şəxsin', '02 - tutulmanı və ya tutulan şəxsin həbsdə saxlanılma yerlərində saxlanılmasını həyata keçirən şəxsin'), ('03 - əməliyyat-axtarış fəaliyyətini həyata keçirən şəxsin', '03 - əməliyyat-axtarış fəaliyyətini həyata keçirən şəxsin'), ('05 - ibtidai araşdırmaya prosessual rəhbərliyi həyata keçirən prokurorun', '05 - ibtidai araşdırmaya prosessual rəhbərliyi həyata keçirən prokurorun')], default='______', max_length=50000)),
                ('bir_instansiya_məhkəməsində_baxılmışdır', models.DateTimeField(blank=True, null=True, verbose_name='I instansiya məhkəməsində baxılmışdır')),
                ('şikayətə_baxılmanın_nəticəsi', models.CharField(choices=[('_____', '______'), ('01 - təmin olunmuşdur', '01 - təmin olunmuşdur'), ('02 - rədd olunmuşdur', '02 - rədd olunmuşdur'), ('03 - aidiyyəti üzrə göndərilmişdir', '03 - aidiyyəti üzrə göndərilmişdir')], default='______', max_length=50000)),
                ('apellyasiya_qayadısnda', models.CharField(choices=[('_____', '______'), ('01 - şikayət verilmişdir', '01 - şikayət verilmişdir'), ('02 - protest verilmişdir', '02 - protest verilmişdir')], default='______', max_length=50000)),
                ('apellyasiya_məhkəməsində_baxılmışdır', models.DateField(blank=True, null=True)),
                ('apellyasiya_məhkəməsi', models.CharField(choices=[('_____', '______'), ('01 - qərarı dəyişdirmədən saxlamışdır', '01 - qərarı dəyişdirmədən saxlamışdır'), ('02 - qərarı ləğv etmişdir', '02 - qərarı ləğv etmişdir')], default='______', max_length=50000)),
                ('iş_dəftərxanaya_təhvil_verilmişdir', models.DateField(blank=True, null=True)),
                ('qeyd', models.CharField(blank=True, max_length=50000, null=True)),
                ('iki_instansiya_mahkemesi_hakimi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='altıkodumahkemehakimiiki', to='apps.ikinciinstansiyamahkemesihakimimodel', verbose_name='Apellyasiyanın hakimi')),
                ('instansiya_mahkemesi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='altıkodumahkeme', to='apps.i̇nstansiyamahkemesimodel', verbose_name='İşə baxan məhkəmə')),
                ('instansiya_mahkemesi_hakimi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='altıkodumahkemehakimi', to='apps.instansiyamahkemesihakimimodel', verbose_name='İşə baxan hakim')),
            ],
            options={
                'verbose_name': 'Altı kodu',
                'verbose_name_plural': 'Altı kodu',
                'ordering': ['id'],
            },
        ),
    ]
