# Generated by Django 3.1 on 2021-10-10 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altıkodu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='altıkodu',
            options={'ordering': ['id'], 'verbose_name': '6 kodu', 'verbose_name_plural': '6 kodu'},
        ),
    ]
