# Generated by Django 3.1 on 2021-10-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altıkodu', '0004_auto_20211010_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altıkodu',
            name='bir_instansiya_məhkəməsində_baxılmışdır',
            field=models.DateField(blank=True, null=True, verbose_name='I instansiya məhkəməsində baxılmışdır'),
        ),
    ]
