# Generated by Django 3.1 on 2021-10-10 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20211010_0317'),
        ('dördkodu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='döddkodu',
            options={'ordering': ['id'], 'verbose_name': '4 kodu', 'verbose_name_plural': '4 kodu'},
        ),
        migrations.AddField(
            model_name='döddkodu',
            name='daxil_olma_tarixi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='döddkodu',
            name='iki_instansiya_mahkemesi_hakimi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='döddmahkemehakimiiki', to='apps.ikinciinstansiyamahkemesihakimimodel', verbose_name='2-ci instansiya məhkəməsinin hakimi'),
        ),
        migrations.AlterField(
            model_name='döddkodu',
            name='qərarından',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qərarından_model', to='apps.i̇nstansiyamahkemesimodel'),
        ),
    ]
