# Generated by Django 3.1 on 2021-10-10 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20211010_0317'),
        ('dördkodu', '0002_auto_20211010_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='döddkodu',
            name='instansiya_mahkemesi_hakimi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dördkodumahkemehakimi', to='apps.instansiyamahkemesihakimimodel', verbose_name='1-ci instansiya məhkəməsi hakimi'),
        ),
    ]
