# Generated by Django 3.1 on 2021-10-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dördkodu', '0004_döddkodu_yoxlanıldı'),
    ]

    operations = [
        migrations.AlterField(
            model_name='döddkodu',
            name='vəsatətin_baxılma_nəticəsi',
            field=models.CharField(choices=[('_____', '______'), ('1 - təmin edilmişdir;', '1 - təmin edilmişdir;'), ('2 - rədd edilmişdir;', '2 - rədd edilmişdir;'), ('3 - aidiyyəti üzrə göndərilmişdir;', '3 - aidiyyəti üzrə göndərilmişdir;')], default='______', max_length=50000),
        ),
    ]
