# Generated by Django 3.1 on 2021-10-22 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dördkodu', '0005_auto_20211022_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='döddkodu',
            name='daxil_olma_tarixi',
        ),
    ]
