# Generated by Django 3.1 on 2021-10-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='erizesikayet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('müraciətin_müəllifi', models.CharField(blank=True, max_length=50000, null=True)),
                ('müraciətin_icraat_üzrə_növü', models.CharField(choices=[('_____', '______'), ('1.Cinayət', '1.Cinayət'), ('2.Hərbi', '2.Hərbi'), ('3.Mülki', '3.Mülki'), ('4.İqtisadi', '4.İqtisadi'), ('5.İnzibati', '5.İnzibati'), ('6.Digər', '6.Digər')], default='______', max_length=500)),
                ('müraciət_daxil_olub', models.CharField(blank=True, max_length=50000, null=True)),
                ('müraciətin_növü', models.CharField(choices=[('_____', '______'), ('Ərizə', 'Ərizə'), ('şikayət', 'şikayət'), ('Təklif', 'Təklif'), ('FFE', 'FFE')], default='______', max_length=500)),
                ('daxil_olma_nömrə_və_tarix', models.DateField(blank=True, null=True)),
                ('birbaşa', models.CharField(choices=[('_____', '______'), ('Poçt', 'Poçt'), ('Elektron poçt', 'Elektron poçt'), ('Vətəndaşdan', 'Vətəndaşdan'), ('Qaynar Xətt', 'Qaynar Xətt'), ('Faks', 'Faks'), ('Digər', 'Digər'), ('Teleqram', 'Teleqram')], default='______', max_length=500)),
                ('dövlət_orqanlarından_və_ya_digər_orqanlardan', models.CharField(choices=[('_____', '______'), ('AR Prezidentinin Adminstrasiyasından', 'AR Prezidentinin Adminstrasiyasından'), ('Milli Məclisdən', 'Milli Məclisdən'), ('Nazirlər Kabinetindən', 'Nazirlər Kabinetindən'), ('Ali Məhkəmədən', 'Ali Məhkəmədən'), ('Ərazi yurisdiksiyaya aid məhkəmələrdən', 'Ərazi yurisdiksiyaya aid məhkəmələrdən')], default='______', max_length=500)),
                ('digər_orqanlardan', models.CharField(blank=True, max_length=50000, null=True)),
                ('nəzarətdədir', models.BooleanField(blank=True, default=False)),
                ('hansı_müddət_müəyyən_edilib', models.CharField(blank=True, max_length=50000, null=True)),
                ('təkrar', models.BooleanField(blank=True, default=False)),
                ('əvvəlki_nömrə_ve_Tarix', models.CharField(blank=True, max_length=50000, null=True)),
                ('daxil_olan_müraciətin_mövzuları', models.CharField(choices=[('_____', '______'), ('1-İşlərə obyektiv baxılmasına köməklik göstərilməsi barədə', '1-İşlərə obyektiv baxılmasına köməklik göstərilməsi barədə'), ('2-Məhkəmə sədrləri tərəfindən qəbul edilmələri barədə', '2-Məhkəmə sədrləri tərəfindən qəbul edilmələri barədə'), ('3-İşlə bağlı məlumat verilməsi', '3-İşlə bağlı məlumat verilməsi'), ('4-Məhkəmə aktları tələbi barədə', '4-Məhkəmə aktları tələbi barədə'), ('5-Vətəndaşların ehtimal olunan hüquqlarının pozulması barədə', '5-Vətəndaşların ehtimal olunan hüquqlarının pozulması barədə'), ('6-Məhkəmə Aktlarının icra olunmaması barədə', '6-Məhkəmə Aktlarının icra olunmaması barədə'), ('7-Məhkəmə Aktlarının birtərəfli qəbul edilməsi barədə', '7-Məhkəmə Aktlarının birtərəfli qəbul edilməsi barədə'), ('8-Məhkəmələrdə süründürməçiliyə yol verilməsi barədə', '8-Məhkəmələrdə süründürməçiliyə yol verilməsi barədə'), ('9-Hakimin qeyri qanuni hərəkətləri barədə', '9-Hakimin qeyri qanuni hərəkətləri barədə'), ('10-Vəkilin qeyri-qanuni hərəkətləri barədə', '10-Vəkilin qeyri-qanuni hərəkətləri barədə'), ('11-Digər', '11-Digər'), ('_____', '______')], default='______', max_length=500)),
                ('müraciətə_baxılmasının_nəticəsi', models.CharField(choices=[('_____', '______'), ('Müsbət həll olunub', 'Müsbət həll olunub'), ('Qismən həll olunub', 'Qismən həll olunub'), ('Müvafiq izah verilib', 'Müvafiq izah verilib'), ('Əsassız sayılıb', 'Əsassız sayılıb'), ('İcradadır', 'İcradadır'), ('Müraciət aidiyyəti üzrə göndərilib', 'Müraciət aidiyyəti üzrə göndərilib'), ('Digər', 'Digər')], default='______', max_length=500)),
                ('digər', models.CharField(blank=True, max_length=50000, null=True)),
                ('müraciətə_baxılma_müddəti', models.CharField(choices=[('_____', '______'), ('3 iş günü', '3 iş günü'), ('5 iş günü', '5 iş günü'), ('10 iş günü', '10 iş günü'), ('15 iş günü', '15 iş günü'), ('30 iş günü', '30 iş günü'), ('30 iş günündən artıq', '30 iş günündən artıq')], default='______', max_length=500)),
                ('qeyd', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'verbose_name': 'erize sikayet',
                'verbose_name_plural': 'erize sikayet',
                'ordering': ['id'],
            },
        ),
    ]
