# Generated by Django 3.1 on 2021-10-10 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erizesikayet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='erizesikayet',
            options={'ordering': ['id'], 'verbose_name': 'Ərizə Şikayət', 'verbose_name_plural': 'Ərizə Şikayət'},
        ),
    ]
