# Generated by Django 3.1 on 2021-10-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erizesikayet', '0002_auto_20211010_0405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='erizesikayet',
            old_name='digər',
            new_name='digər_daxil_olan_müraciətin_mövzuları',
        ),
        migrations.AddField(
            model_name='erizesikayet',
            name='digər_müraciətin_icraat_üzrə_növü',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='erizesikayet',
            name='digər_müraciətə_baxılmasının_nəticəsi',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
