# Generated by Django 3.1 on 2021-10-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erizesikayet', '0004_erizesikayet_yoxlanıldı'),
    ]

    operations = [
        migrations.RenameField(
            model_name='erizesikayet',
            old_name='daxil_olma_nömrə_və_tarix',
            new_name='daxil_olma_nömrə',
        ),
        migrations.AddField(
            model_name='erizesikayet',
            name='daxil_olma_tarix',
            field=models.DateField(blank=True, null=True),
        ),
    ]
