# Generated by Django 3.1 on 2021-09-25 00:03

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0002_auto_20210925_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinayetİsinNovları',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
            ],
            options={
                'verbose_name': 'Cinayet İşin Növü',
                'verbose_name_plural': 'Cinayet İşin Növları',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sikayətverilmisdir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
            ],
            options={
                'verbose_name': 'Şikayət verilmişdir',
                'verbose_name_plural': 'Şikayət verilmişdir',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cinayet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('növ', models.CharField(choices=[('1', '1'), ('1-1', '1-1')], default='1', max_length=50)),
                ('birinci_şəxs', models.BooleanField(blank=True, default=False)),
                ('dahil_olmuşdur', models.DateTimeField(blank=True, null=True)),
                ('təqsirləndirilən_şəxs', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('Şikayət_Protest', models.CharField(choices=[('Şikayət', 'Şikayət'), ('Protest', 'Protest'), ('Şikayət və protest', 'Şikayət və protest')], default='Şikayət', max_length=50)),
                ('etiraz', models.CharField(choices=[('01 təmin edilmişdir', '01 təmin edilmişdir'), ('02 rədd edilmişdir', '02 rədd edilmişdir'), ('03 - baxılmamış saxlanılmışdır', '03 - baxılmamış saxlanılmışdır')], default='01 təmin edilmişdir', max_length=50)),
                ('baxılmamışdır', models.CharField(choices=[('_____', '______'), ('_____', '______'), ('_____', '______'), ('_____', '______'), ('_____', '______')], default='CPM 384-387-ci maddələrin tələbləri', max_length=50)),
                ('hökm_dəyişdirilmədən_saxlanılmışdır', models.BooleanField(blank=True, default=False)),
                ('hökm_ləğv_edilib_yeni_hökm_çıxarılıb', models.CharField(choices=[('Düzgün bəraət olunmadığına görə', 'Düzgün bəraət olunmadığına görə'), ('Cinayət tərkibi əməli və ittiham sübuta yetirilmədiyindən', 'Cinayət tərkibi əməli və ittiham sübuta yetirilmədiyindən'), ('Cinayət qanunu normasının düzgün tətbiq edilməməsi', 'Cinayət qanunu normasının düzgün tətbiq edilməməsi'), ('Digər əsaslar', 'Digər əsaslar')], default='Düzgün bəraət olunmadığına görə', max_length=5000)),
                ('hökm_ləğv_edilib_icraata_xitam_verilib', models.CharField(choices=[('Düzgün bəraət olunmadığına görə', 'Düzgün bəraət olunmadığına görə'), ('Cinayət tərkibi əməli və ittiham sübuta yetirilmədiyindən', 'Cinayət tərkibi əməli və ittiham sübuta yetirilmədiyindən'), ('Cinayət qanunu normasının düzgün tətbiq edilməməsi', 'Cinayət qanunu normasının düzgün tətbiq edilməməsi'), ('Digər əsaslar', 'Digər əsaslar')], default='Düzgün bəraət olunmadığına görə', max_length=5000)),
                ('hökm_ləğv_edilib_yeni_baxışa_göndərilib', models.CharField(choices=[('Düzgün bəraət olunmadığına görə', 'Düzgün bəraət olunmadığına görə'), ('Cinayət tərkibi əməli və ittiham sübuta yetirilmədiyindən', 'Cinayət tərkibi əməli və ittiham sübuta yetirilmədiyindən'), ('Cinayət qanunu normasının düzgün tətbiq edilməməsi', 'Cinayət qanunu normasının düzgün tətbiq edilməməsi'), ('Digər əsaslar', 'Digər əsaslar')], default='Düzgün bəraət olunmadığına görə', max_length=5000)),
                ('qərar', models.CharField(choices=[('Dəyişdirilmədən saxlanılmışdır', 'Dəyişdirilmədən saxlanılmışdır'), ('Qərar ləğv edilmişdir', 'Qərar ləğv edilmişdir'), ('Qərar dəyişdirilmişdir', 'Qərar dəyişdirilmişdir')], default='Dəyişdirilmədən saxlanılmışdır', max_length=5000)),
                ('hökm_dəyişdirilmişdir', models.CharField(choices=[('Cəzanın ağırlaşdırılması', 'Cəzanın ağırlaşdırılması'), ('Cəzanın yüngülləşdirilməsi', 'Cəzanın yüngülləşdirilməsi'), ('Digər Əsaslar', 'Digər Əsaslar')], default='Cəzanın ağırlaşdırılması', max_length=5000)),
                ('xüsusi_Qərar', models.CharField(choices=[('dövlət orqanının vəzifəli şəxsləri barəsində', 'dövlət orqanının vəzifəli şəxsləri barəsində'), ('müstəntiqlər, təhqiqatçılar və təhqiqat orqanının əməkdaşları', 'müstəntiqlər, təhqiqatçılar və təhqiqat orqanının əməkdaşları'), ('prokurorlar və ya prokurorluğun müstəntiqləri barəsində', 'prokurorlar və ya prokurorluğun müstəntiqləri barəsində'), ('birinci instansiya məhkəməsinin hakimləri barəsində', 'birinci instansiya məhkəməsinin hakimləri barəsində')], default='dövlət orqanının vəzifəli şəxsləri barəsində', max_length=5000)),
                ('dəftərxanaya_təhvil_verildi', models.DateTimeField(blank=True, null=True)),
                ('qeyd', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('Sikayət_verilmisdir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sikayətverilmisdirmodel', to='apps.instansiyamahkemesihakimimodel')),
                ('iki_instansiya_mahkemesi_hakimi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cinayetmahkemehakimiiki', to='apps.ikinciinstansiyamahkemesihakimimodel')),
                ('instansiya_mahkemesi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cinayetmahkeme', to='apps.i̇nstansiyamahkemesimodel')),
                ('instansiya_mahkemesi_hakimi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cinayetmahkemehakimi', to='apps.instansiyamahkemesihakimimodel')),
                ('isin_novu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cinayətin_növləri', to='cinayet.cinayeti̇sinnovları', verbose_name='Cinayətin növləri')),
            ],
            options={
                'verbose_name': 'Cinayet',
                'verbose_name_plural': 'Cinayet',
                'ordering': ['id'],
            },
        ),
    ]
