# Generated by Django 3.1 on 2021-09-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinayet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinayet',
            name='baxılmamışdır',
            field=models.CharField(choices=[('_____', '______'), ('_____', '______'), ('_____', '______'), ('_____', '______'), ('_____', '______')], default='______', max_length=50),
        ),
        migrations.AlterField(
            model_name='cinayet',
            name='etiraz',
            field=models.CharField(choices=[('_____', '______'), ('01 təmin edilmişdir', '01 təmin edilmişdir'), ('02 rədd edilmişdir', '02 rədd edilmişdir'), ('03 - baxılmamış saxlanılmışdır', '03 - baxılmamış saxlanılmışdır')], default='______', max_length=50),
        ),
        migrations.AlterField(
            model_name='cinayet',
            name='hökm_dəyişdirilmişdir',
            field=models.CharField(choices=[('_____', '______'), ('Cəzanın ağırlaşdırılması', 'Cəzanın ağırlaşdırılması'), ('Cəzanın yüngülləşdirilməsi', 'Cəzanın yüngülləşdirilməsi'), ('Digər Əsaslar', 'Digər Əsaslar')], default='______', max_length=5000),
        ),
        migrations.AlterField(
            model_name='cinayet',
            name='hökm_ləğv_edilib_icraata_xitam_verilib',
            field=models.CharField(choices=[('_____', '______'), ('Düzgün bəraət olunmadığına görə', 'Düzgün bəraət olunmadığına görə'), ('Cinayət tərkibi əməli və ittiham sübuta yetirilmədiyindən', 'Cinayət tərkibi əməli və ittiham sübuta yetirilmədiyindən'), ('Cinayət qanunu normasının düzgün tətbiq edilməməsi', 'Cinayət qanunu normasının düzgün tətbiq edilməməsi'), ('Digər əsaslar', 'Digər əsaslar')], default='______', max_length=5000),
        ),
        migrations.AlterField(
            model_name='cinayet',
            name='hökm_ləğv_edilib_yeni_baxışa_göndərilib',
            field=models.CharField(choices=[('_____', '______'), ('Düzgün bəraət olunmadığına görə', 'Düzgün bəraət olunmadığına görə'), ('Cinayət tərkibi əməli və ittiham sübuta yetirilmədiyindən', 'Cinayət tərkibi əməli və ittiham sübuta yetirilmədiyindən'), ('Cinayət qanunu normasının düzgün tətbiq edilməməsi', 'Cinayət qanunu normasının düzgün tətbiq edilməməsi'), ('Digər əsaslar', 'Digər əsaslar')], default='______', max_length=5000),
        ),
        migrations.AlterField(
            model_name='cinayet',
            name='hökm_ləğv_edilib_yeni_hökm_çıxarılıb',
            field=models.CharField(choices=[('_____', '______'), ('Düzgün bəraət olunmadığına görə', 'Düzgün bəraət olunmadığına görə'), ('Cinayət tərkibi əməli və ittiham sübuta yetirilmədiyindən', 'Cinayət tərkibi əməli və ittiham sübuta yetirilmədiyindən'), ('Cinayət qanunu normasının düzgün tətbiq edilməməsi', 'Cinayət qanunu normasının düzgün tətbiq edilməməsi'), ('Digər əsaslar', 'Digər əsaslar')], default='______', max_length=5000),
        ),
        migrations.AlterField(
            model_name='cinayet',
            name='növ',
            field=models.CharField(choices=[('_____', '______'), ('1', '1'), ('1-1', '1-1')], default='______', max_length=50),
        ),
        migrations.AlterField(
            model_name='cinayet',
            name='qərar',
            field=models.CharField(choices=[('_____', '______'), ('Dəyişdirilmədən saxlanılmışdır', 'Dəyişdirilmədən saxlanılmışdır'), ('Qərar ləğv edilmişdir', 'Qərar ləğv edilmişdir'), ('Qərar dəyişdirilmişdir', 'Qərar dəyişdirilmişdir')], default='______', max_length=5000),
        ),
        migrations.AlterField(
            model_name='cinayet',
            name='xüsusi_Qərar',
            field=models.CharField(choices=[('_____', '______'), ('dövlət orqanının vəzifəli şəxsləri barəsində', 'dövlət orqanının vəzifəli şəxsləri barəsində'), ('müstəntiqlər, təhqiqatçılar və təhqiqat orqanının əməkdaşları', 'müstəntiqlər, təhqiqatçılar və təhqiqat orqanının əməkdaşları'), ('prokurorlar və ya prokurorluğun müstəntiqləri barəsində', 'prokurorlar və ya prokurorluğun müstəntiqləri barəsində'), ('birinci instansiya məhkəməsinin hakimləri barəsində', 'birinci instansiya məhkəməsinin hakimləri barəsində')], default='______', max_length=5000),
        ),
        migrations.AlterField(
            model_name='cinayet',
            name='Şikayət_Protest',
            field=models.CharField(choices=[('_____', '______'), ('Şikayət', 'Şikayət'), ('Protest', 'Protest'), ('Şikayət və protest', 'Şikayət və protest')], default='______', max_length=50),
        ),
    ]
