# Generated by Django 3.1 on 2021-10-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinayet', '0002_auto_20211001_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinayet',
            name='dahil_olmuşdur',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cinayet',
            name='dəftərxanaya_təhvil_verildi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
