# Generated by Django 3.1 on 2021-10-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinayet', '0004_auto_20211010_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinayet',
            name='dahil_olmuşdur',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cinayet',
            name='dəftərxanaya_təhvil_verildi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
