# Generated by Django 3.1 on 2021-10-10 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinayet', '0006_auto_20211010_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinayet',
            name='Sikayət_verilmisdir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sikayətverilmisdirmodel', to='cinayet.sikayətverilmisdir'),
        ),
    ]
