# Generated by Django 3.1 on 2021-10-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinayet', '0009_auto_20211010_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinayet',
            name='yoxlanıldı',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
