# Generated by Django 3.1 on 2021-10-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinayet', '0010_cinayet_yoxlanıldı'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinayet',
            name='etiraz',
            field=models.CharField(choices=[('_____', '______'), ('1 təmin edilmişdir', '1 təmin edilmişdir'), ('2 rədd edilmişdir', '2 rədd edilmişdir'), ('3 - baxılmamış saxlanılmışdır', '3 - baxılmamış saxlanılmışdır')], default='______', max_length=50),
        ),
    ]
