# Generated by Django 3.1 on 2021-10-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinayet', '0011_auto_20211022_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinayet',
            name='baxılmamışdır',
            field=models.CharField(choices=[('_____', '______'), ('CPM 384-387-ci maddələrin tələbləri', 'CPM 384-387-ci maddələrin tələbləri'), ('CPM 385-388-ci maddələrin tələbləri', 'CPM 385-388-ci maddələrin tələbləri'), ('apellyasiya şikayətinə xitam', 'apellyasiya şikayətinə xitam'), ('digər', 'digər')], default='______', max_length=50),
        ),
        migrations.AlterField(
            model_name='cinayet',
            name='dahil_olmuşdur',
            field=models.DateField(blank=True, null=True, verbose_name='Daxil olmuşdur'),
        ),
        migrations.AlterField(
            model_name='cinayet',
            name='təqsirləndirilən_şəxs',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
