# Generated by Django 3.1 on 2021-11-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinayet', '0012_auto_20211023_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinayet',
            name='işin_nömrəsi',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
