# Generated by Django 3.1 on 2021-09-07 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ikinciinstansiyaMahkemesihakimiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
            ],
            options={
                'verbose_name': 'İnstansiya Mahkemesi Hakimi',
                'verbose_name_plural': 'İnstansiya Mahkemesi Hakimleri',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='instansiyaMahkemesihakimiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
            ],
            options={
                'verbose_name': 'İnstansiya Mahkemesi Hakimi',
                'verbose_name_plural': 'İnstansiya Mahkemesi Hakimleri',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='İnstansiyaMahkemesiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
            ],
            options={
                'verbose_name': 'İnstansiya Mahkemesi',
                'verbose_name_plural': 'İnstansiya Mahkemeleri',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='İsinNovlarıModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
            ],
            options={
                'verbose_name': 'İşin Növü',
                'verbose_name_plural': 'İşin Növları',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NeticaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
            ],
            options={
                'verbose_name': 'Netica',
                'verbose_name_plural': 'Neticalar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mülki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin_nömresi', models.CharField(max_length=50)),
                ('dahil_olmuşdur', models.DateTimeField(blank=True, null=True)),
                ('apellyasiya_sikayati_verilmişdir', models.CharField(choices=[('qatname', 'Qatname'), ('qarardad', 'Qarardad'), ('qarar', 'Qarar'), ('etiraz', 'Etiraz'), ('aidiyyat', 'Aidiyyat')], default='qatname', max_length=50)),
                ('iddiaçı', models.TextField(blank=True, max_length=10000, null=True)),
                ('cavabdeh', models.TextField(blank=True, max_length=10000, null=True)),
                ('iddianın_maliyeti', models.TextField(blank=True, max_length=10000, null=True)),
                ('hakima_edilmiş_etiraz', models.CharField(choices=[('tamin edilmiştir', 'Tamin Edilmişdir'), ('red edilmiştir', 'Red edilmişdir')], default='tamin edilmiştir', max_length=50)),
                ('qeyri_mümkün_hesab_edilerek_icraata_xitam_verilmişdir', models.CharField(choices=[('mpm-in 366-cı maddasi üzra', 'MPM-in 366-cı maddasi üzra'), ('mpm-in 369-cu maddasi üzra', 'MPM-in 369-cu maddasi üzra'), ('mpm-in 370-cı maddasi üzra', 'MPM-in 370-cı maddasi üzra'), ('Baxılmadan geri qaytarıldı', 'Baxılmadan geri qaytarıldı')], default='mpm-in 366-cı maddasi üzra', max_length=50)),
                ('aidiyyat', models.BooleanField(blank=True, default=False)),
                ('apellyasiya_qaydasında_bakılmısdır', models.TextField(blank=True, max_length=10000, null=True)),
                ('yekun_qarar', models.CharField(choices=[('qatnama', 'Qatnama'), ('qarardad', 'Qarardad'), ('qarar', 'Qarar')], default='qatnama', max_length=50)),
                ('xüsusi_wawrardad', models.CharField(blank=True, max_length=500, null=True)),
                ('dövlat_rüsumu', models.CharField(blank=True, max_length=500, null=True)),
                ('qısa_qeyd', models.CharField(blank=True, max_length=500, null=True)),
                ('deftarxanaya_tahvil_verildi', models.DateTimeField(blank=True, null=True)),
                ('qeyd', models.TextField(blank=True, max_length=100000, null=True)),
                ('iki_instansiya_mahkemesi_hakimi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mahkemehakimiiki', to='apps.ikinciinstansiyamahkemesihakimimodel')),
                ('instansiya_mahkemesi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mahkeme', to='apps.i̇nstansiyamahkemesimodel')),
                ('instansiya_mahkemesi_hakimi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mahkemehakimi', to='apps.instansiyamahkemesihakimimodel')),
                ('isin_novu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='növ', to='apps.i̇sinnovlarımodel')),
                ('netica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='netica', to='apps.neticamodel')),
            ],
        ),
    ]
