# Generated by Django 3.1 on 2021-09-25 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mülki',
            name='iki_instansiya_mahkemesi_hakimi',
        ),
        migrations.RemoveField(
            model_name='mülki',
            name='instansiya_mahkemesi',
        ),
        migrations.RemoveField(
            model_name='mülki',
            name='instansiya_mahkemesi_hakimi',
        ),
        migrations.RemoveField(
            model_name='mülki',
            name='isin_novu',
        ),
        migrations.RemoveField(
            model_name='mülki',
            name='netica',
        ),
        migrations.DeleteModel(
            name='İsinNovlarıModel',
        ),
        migrations.DeleteModel(
            name='Mülki',
        ),
        migrations.DeleteModel(
            name='NeticaModel',
        ),
    ]
