# Generated by Django 3.1 on 2021-10-10 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20210925_0303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ikinciinstansiyamahkemesihakimimodel',
            options={'ordering': ['id'], 'verbose_name': 'Apelyasiya məhkəməsi hakim', 'verbose_name_plural': 'Apelyasiya məhkəməsi hakimləri'},
        ),
        migrations.AlterModelOptions(
            name='instansiyamahkemesihakimimodel',
            options={'ordering': ['id'], 'verbose_name': '1-ci instansiya məhkəməsinin hakim', 'verbose_name_plural': '1-ci instansiya məhkəməsinin hakimləri'},
        ),
        migrations.AlterModelOptions(
            name='i̇nstansiyamahkemesimodel',
            options={'ordering': ['id'], 'verbose_name': '1-ci instansiya', 'verbose_name_plural': '1-ci instansiyalar'},
        ),
    ]
