# Generated by Django 3.1 on 2021-10-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inziqtmul', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inziqmul',
            name='qeyd',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
