# Generated by Django 3.1 on 2021-10-10 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20211010_0317'),
        ('inziqtmul', '0002_auto_20211002_0212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inziqmul',
            options={'ordering': ['id'], 'verbose_name': 'İNZ İQT MUL (inzibati, iqtisadi, mülki)', 'verbose_name_plural': 'İNZ İQT MUL (inzibati, iqtisadi, mülki)'},
        ),
        migrations.AlterField(
            model_name='inziqmul',
            name='iki_instansiya_mahkemesi_hakimi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inziqmulmahkemehakimiiki', to='apps.ikinciinstansiyamahkemesihakimimodel', verbose_name='2-ci instansiya məhkəməsinin hakimi'),
        ),
        migrations.AlterField(
            model_name='inziqmul',
            name='qeyri_mümkün_hesab_edilərək_icraata_xitam_verilmişdir',
            field=models.CharField(choices=[('_____', '______'), ('01 - MPM-in 366-cı maddəsi üzrə', '01 - MPM-in 366-cı maddəsi üzrə'), ('02 - MPM-in 369-cu maddəsi üzrə', '02 - MPM-in 369-cu maddəsi üzrə'), ('03 - MPM-in 370-ci maddəsi üzrə', '03 - MPM-in 370-ci maddəsi üzrə'), ('04 - Baxılmadan geri qaytarıldı', '04 - Baxılmadan geri qaytarıldı')], default='______', max_length=50),
        ),
    ]
