# Generated by Django 3.1 on 2021-10-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inziqtmul', '0003_auto_20211010_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inziqmulisinnovları',
            name='name',
            field=models.CharField(max_length=100, verbose_name='İşin növünü əlavə et'),
        ),
    ]
