# Generated by Django 3.1 on 2021-10-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inziqtmul', '0005_inziqmul_yoxlanıldı'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inziqmul',
            name='hakimə_edilmiş_etiraz',
            field=models.CharField(choices=[('_____', '______'), ('1 təmin edilmişdir', '1 təmin edilmişdir'), ('2 rədd edilmişdir', '2 rədd edilmişdir')], default='______', max_length=5000),
        ),
        migrations.AlterField(
            model_name='inziqmul',
            name='qeyri_mümkün_hesab_edilərək_icraata_xitam_verilmişdir',
            field=models.CharField(choices=[('_____', '______'), ('1 - MPM-in 366-cı maddəsi üzrə', '1 - MPM-in 366-cı maddəsi üzrə'), ('2 - MPM-in 369-cu maddəsi üzrə', '2 - MPM-in 369-cu maddəsi üzrə'), ('3 - MPM-in 370-ci maddəsi üzrə', '3 - MPM-in 370-ci maddəsi üzrə'), ('4 - Baxılmadan geri qaytarıldı', '4 - Baxılmadan geri qaytarıldı')], default='______', max_length=50),
        ),
        migrations.AlterField(
            model_name='inziqmul',
            name='xüsusi_Qərar',
            field=models.CharField(choices=[('_____', '______'), ('1 - çıxarılmışdır', '1 - çıxarılmışdır'), ('2 - çıxarılmamışdır', '2 - çıxarılmamışdır'), ('3 - hakim barəsində', '3 - hakim barəsində')], default='______', max_length=5000),
        ),
    ]
