# Generated by Django 3.1 on 2021-10-22 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inziqtmul', '0006_auto_20211022_2347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inziqmul',
            options={'ordering': ['id'], 'verbose_name': 'İNZ İQT MUL', 'verbose_name_plural': 'İNZ İQT MUL '},
        ),
    ]
